### ISSUE TITLE
isomorphic

### ISSUE THREAD

**Issue by Kflash** [babel/generator-babel-boilerplate#271]
I saw you are creating a v. 6.0. Excelent work!

Time to consider isomorphic? Very easy to do that with webpack.

If not support right out of the box, add it as a option flag maybe?

**Comment by jmeas** [comment]
Hey there, @kflash. Thanks for the suggestion!

Isomorphic JavaScript seems cool, but I don't use it myself. Since it's easy enough to set up, maybe this is one of those features that individuals should set up *after* scaffolding a new project with the boilerplate?

One of the things I like about this boilerplate is that it's the bare minimum of what I want in every project, be it a little library, or a webapp, or whatever. Sometimes I need to tweak it after I clone it, but that's okay. It still provides me with a good foundation. I'm thinking this is one of those things that can be added to the solid foundation in the projects you want to use it on.

What do you think?

**Comment by Kflash** [comment]
@jmeas Just mention it in the readme maybe?

**Comment by jmeas** [comment]
If I mentioned everything that Webpack can do in the README, then I'd just be recreating the docs of webpack, right? I don't think isomorphic support stands out as a particularly special thing.

If you wanted, I could just add that it's built with Webpack, and that should be enough?

**Comment by Kflash** [comment]
I think it should be enough. Basicly its all about index.js and server.js

**Comment by jmeas** [comment]
Gonna close this in favor of #84. The webpage will talk about the technologies used in the boilerplate, including Webpack and what ya can do with that.
