### ISSUE TITLE
Possible to get rid of Webpack?

### ISSUE THREAD

**Issue by marcandre** [babel/generator-babel-boilerplate#325]
I upgraded `generator-babel-boilerplate` and wanted to use it for a small library (50 loc). Damn, what is this huge mess of a header? 😦   The first 67 lines of my resulting js files is obscure webpack stuff.

As far as I'm concerned, that's simply not acceptable. I don't understand what webpack is, what it's for, but one thing is for certain: I do not feel I need it and I don't want it. Now I have to figure out how to use an older version of `generator-babel-boilerplate`. 😢

**Comment by jmeas** [comment]
Hey again @marcandre ! Thanks for raising the issue.

> Now I have to figure out how to use an older version of generator-babel-boilerplate. 😢

You can go to a previous version via:

`npm i generator-babel-boilerplate@^6 -g`

This will globally install the version before Webpack was introduced.

> Damn, what is this huge mess of a header? 😦 The first 67 lines of my resulting js files is obscure webpack stuff.

I know, I know. Ugly, right? I think it's a little excessive, but it does compile down to [a competitive size](https://github.com/samccone/The-cost-of-transpiling-es2015-in-2016). So despite its ugliness, it's not creating too much extra bulk when your library is being consumed.

> As far as I'm concerned, that's simply not acceptable. I don't understand what webpack is, what it's for, 

I get why you might feel this way. I'm not too concerned with the output files of my libs (folks should only look at src files, I think), which is why this doesn't bother me but I totally get why someone might care :)

You'll be happy to hear that @paulfalgout and I have been talking about removing Webpack from this boilerplate, and I'll likely tackle that in the next week or two. We'll be moving to Rollup (#319, which has very nice output imo.

Sorry for the trouble! And keep an eye out for that next version :)

**Comment by marcandre** [comment]
Ok, cool.

Please realize that for many people that want to incorporate a library in their project, they will not have access to the `src` files, they will be using the uncompressed `dist/` files (either directly or with `npm` / `bower` / etc...). That's why I care about the `dist/` file...

Closing, since there's already an issue about this (sorry I didn't see it)

**Comment by paulfalgout** [comment]
I would hope the uncompressed file would ultimately get compressed in the various project's builds, and in those cases webpack compresses well.  But I feel ya.  Recent improvements to rollup are making it a great option that I think you'll enjoy.

**Comment by jmeas** [comment]
> Please realize that for many people that want to incorporate a library in their project, they will not have access to the src files, they will be using the uncompressed dist/ files (either directly or with npm / bower / etc...). That's why I care about the dist/ file...

That makes sense :v:

> Closing, since there's already an issue about this (sorry I didn't see it)

No problem :)

> Recent improvements to rollup are making it a great option that I think you'll enjoy.

Yeah, I'm excited about the switch!
